/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./ui/**/*.{html,ts,tsx,js,jsx}",
    "./ui/pages/*.{html,ts}",
    "./ui/*.{html,ts,tsx,js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primaryRing: "#c3c0ff",
        "surface-variant": "#353534",
        "on-primary": "#1d00a5",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004c69",
        "surface-bright": "#393939",
        tertiary: "#ffb695",
        "on-secondary-container": "#00374d",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#c3c0ff",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#ffb695",
        outline: "#918fa1",
        surface: "#131313",
        "outline-variant": "#464555",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        background: "#131313",
        "on-primary-fixed-variant": "#3323cc",
        "on-background": "#e5e2e1",
        "on-secondary": "#00354a",
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface-container": "#201f1f",
        "on-tertiary-container": "#ffd2be",
        "secondary-fixed": "#c4e7ff",
        "on-secondary-fixed": "#001e2c",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#7cd0ff",
        "primary-container": "#4f46e5",
        "surface-tint": "#c3c0ff",
        "surface-container-high": "#2a2a2a",
        primary: "#c3c0ff",
        error: "#ffb4ab",
        "inverse-primary": "#4d44e3",
        "tertiary-container": "#a44100",
        "on-surface-variant": "#c7c4d8",
        secondary: "#7cd0ff",
        "on-tertiary": "#571f00",
        "on-tertiary-fixed": "#351000",
        "surface-container-low": "#1c1b1b",
        "secondary-container": "#00a6e0",
        "on-primary-fixed": "#0f0069",
        "on-primary-container": "#dad7ff",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
        mono: ["JetBrains Mono"],

        fontSize: {
          base: "20px",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
